version: 0.0
os: linux
files:
  - source: / 
    destination: /usr/local/flaskapp

hooks:
  ApplicationStop:
    - location: stop_old_flask_app.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_flask_app.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: validate_flask_app.sh
      timeout: 300
      runas: root
