version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ec2-user/my-flask-app 

permissions:
  - object: /home/ec2-user/my-flask-app
    pattern: '**/*'
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: stop_old_flask_app.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_flask_app.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: validate_flask_app.sh
      timeout: 300
      runas: ec2-user
