version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
  discard-paths: yes
